name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.5.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.3.3
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  path_provider: ^2.1.1
