name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.8.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  rxdart: ^0.28.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  http: ^1.2.1